### ISSUE TITLE
Cards are empty when using latest Jira interface

### ISSUE THREAD

**Issue by mariapso** [qoomon/Jira-Issue-Card-Printer#55] opened 2017-10-13 10:31 UTC
Hello,

This week Atlassian released a new version of Jira and, when using the new interface, we started having this issue. The cards are empty and an error message pops up.

See the screenshot attached for details.

![print_issue](https://user-images.githubusercontent.com/32766866/31542380-a67f6072-b009-11e7-9573-ee7545f3b28a.jpeg)

The cards are not empty and no error is hit when reverting to use the previous version of Jira interface.

Cheers!

**Comment by rpelaez** [comment] 2017-10-13 18:32
Hi team,

The problem is the line 7 of  jira-issue-tracker.js
In the new Jira UX the result is empty of return $("input[title='baseURL']").attr('value');
If you comment the line 7 works.
I think is better using only  return window.location.origin; it works in the old and in the new UX of JIRA

Best regards!

**Comment by qoomon** [comment] 2017-10-14 23:20
@rpelaez thx i will fix that tomorrow

**Comment by qoomon** [comment] 2017-10-15 10:32
Should be fixed with v5.2.11 434f4c5

**Closed** 2017-10-15 10:33 UTC
Labels: bug

**Comment by mariapso** [comment] 2017-10-16 10:41
Thanks a lot!
