### ISSUE TITLE
Support Jira "next-gen project"

### ISSUE THREAD

**Issue by marlonbosse** [qoomon/Jira-Issue-Card-Printer#71] opened 2019-02-08 10:58 UTC
Currently it's not possible to print anything in "next gen projects" of Jira, an alert with following text show up.

```javascript
{
    "readyState": 4,
    "responseText": "{\"errorMessages\":[\"Issue does not exist or you do not have permission to see it.\"],\"errors\":{}}",
    "responseJSON": {
        "errorMessages": [
            "Issue does not exist or you do not have permission to see it."
        ],
        "errors": {}
    },
    "status": 404,
    "statusText": "error"
}
```

**Comment by qoomon** [comment] 2019-02-08 14:35
Hi, is there any (public) instance where I can have look at? If so i think i can fix it with ease.

**Comment by rpelaez** [comment] 2019-02-08 14:47
Hi Bengt, Atlassian has released a new projects called (next-gen) and they have obfuscated the DOM code.... see more here: https://mraddon.blog/2019/01/14/atlassian-is-obfuscating-jira-cloud-why/

About a Jira Cloud free instance for development, please follow these instructions:
https://mraddon.blog/2016/05/11/new-jira-cloud-development-environment-free/

Best regards!

**Comment by qoomon** [comment] 2019-02-08 16:36
The issue is the obfuscation of their classes, I need to have a javascript snippet to get all selected issue keys like `NEX-123`, however its not that easy anymore.
I've added some hacky workaround code, however I'm not sure if this will be stable at all.
For me the board view of 'next gen projects' works for me.

**Comment by qoomon** [comment] 2019-02-08 16:39
Another workaround is to select all your issues you like to print from `https://<URL_OF_YOUR_JIRA>/issues` and select the list view (not the one with the preview panel, because than you can only print the selected issue), here the card print will work as expected.

**Comment by qoomon** [comment] 2019-02-09 20:50
its broken again :-/. any ideas?

**Comment by rpelaez** [comment] 2019-02-10 10:45
Hi Bengt, I see it working! To select the tickets in the next-gen boards you must use "Cmd" key in Mac. The "Shift" key only works in the old boards.

**Comment by rpelaez** [comment] 2019-02-10 10:45
![captura de pantalla 2019-02-10 a las 11 43 09](https://user-images.githubusercontent.com/1374732/52532689-5f762c80-2d29-11e9-888e-24bf7ae71b09.png)
![captura de pantalla 2019-02-10 a las 11 42 23](https://user-images.githubusercontent.com/1374732/52532692-613ff000-2d29-11e9-90d3-375c601518fd.png)

**Comment by qoomon** [comment] 2019-02-10 12:17
For some reasons it only works on Kannan board. Maybe they are developing actively on the scrum board and therefore the class "hash values" changed more often. 
Do anyone know how this obfuscation works?

**Comment by rpelaez** [comment] 2019-02-10 19:32
Hi Bengt, In the next-gen scrum boards it works
![captura de pantalla 2019-02-10 a las 20 31 25](https://user-images.githubusercontent.com/1374732/52538441-f0252a80-2d72-11e9-8d9d-58b14f2704b3.png)
![Uploading Captura de pantalla 2019-02-10 a las 20.31.19.png…]()

**Comment by rpelaez** [comment] 2019-02-10 19:37
In the old SCRUM and KANBAN it works fine (checked) and in the new next-gen also works fine!
About the obfuscation in your case I think there is no problem Bengt!

I think Atlassian is using this https://stackoverflow.com/questions/50870666/css-class-names-in-atlassians-jira-are-obfuscated

**Comment by qoomon** [comment] 2019-02-10 20:23
In dead it works :-D
okay then i will close this issue for now. please reopen if it stops working again.

**Comment by rpelaez** [comment] 2019-02-10 20:29
I have checked again and it works fine in all boards, except in the backlog of the next-gen projects. I do not understand how it was working a little time ^^ (the proof is the screenshot!)

The new screenshot:
![captura de pantalla 2019-02-10 a las 21 28 47](https://user-images.githubusercontent.com/1374732/52539139-f6b7a000-2d7a-11e9-911d-b5f94ee4ccd1.png)

**Comment by qoomon** [comment] 2019-02-10 20:39
I made some test as well and it seams to work sometimes and sometimes it does not. The css classes changes for some reasons in an unpredictable way 😮

**Comment by rpelaez** [comment] 2019-02-10 21:36
Ooopssss then probably is impossible... :S

**Comment by qoomon** [comment] 2019-05-06 20:40
I might found a way to fix it, find selected issues by background color, little hacky but it seems to work
```
Array.from(document.querySelectorAll('div[tabindex]')).filter((element) => {
    let style = getComputedStyle(element);
    return ( style.backgroundColor == 'rgb(222, 235, 255)' );
}) 
```

**Comment by qoomon** [comment] 2019-05-06 21:14
I've released a fix. please confirm.

**Comment by rpelaez** [comment] 2019-05-07 18:47
Wow amazing trick! I will test this weekend! Thanks Bengt

**Comment by qoomon** [comment] 2019-05-07 20:17
Actually I don't understand why i didn't have this idea before. It is the most obvious solution to select by visual colors :-D

**Closed by qoomon** 2019-05-07 20:17 UTC
Labels: bug, help wanted

**Comment by rpelaez** [comment] 2019-05-12 20:22
It worked wonders! Spectacular! Thanks Bengt
