### ISSUE TITLE
Page / Issue / Title format

### ISSUE THREAD

**Issue by tommyd3mdi** [qoomon/Jira-Issue-Card-Printer#12] opened 2015-02-05 09:09 UTC
I just stumbled over this very useful and awesome bookmarklet, thanks a bunch for this!

A small feature request, though: Would it be possible to restrict the size / height of an issue so that one can always print out two issues on one A4 page? I believe the only way to do this properly is to calculate the final text box' height and reduce its font size until it fits into the given format.

The same would be needed for the summary field. Some of my issues have quite long texts, so in order to not break the layout it would be great if that text scales, too.

Thanks again!

**Comment by qoomon** [comment] 2015-02-08 11:20
For simplicity i choose the one issue per paper policy so you don't need to have scissor around you :-)
However i may can add a checkbox to choose whether to break after each issue or not.

Feature Hint:
If you type *Attachment* in your jira issue everything below is hidden for printing and a paper clip badge will be added on the card, so you know there is more information for this issue.

I hope I could help you out
Regard
Bengt

**Comment by qoomon** [comment] 2015-04-17 23:56
Duplicate of #15

**Closed by qoomon** 2015-04-17 23:56 UTC
Labels: duplicate, enhancement
